version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: /backend
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - /backend/.env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: "on-failure"
    ports:
      - 5432:5432
    env_file:
      - /backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - 80:80

  carbone:
    image: carbone-env-docker
    platform: linux/amd64
    ports:
      - "4000:4000"


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


volumes:
  postgres:
    name: nest-db
